### PR TITLE
Separate data and geometry

### PR DESCRIPTION
**Pull request by rebfrank**
Here's a first pass at pulling data about school discipline from separate data files than the geojson files describing the district geometry. I think this is ready for review but the whole flow (data + display) needs more integration testing before we merge.

Right now it doesn't modify the geojson files at all, it just doesn't use the data from the geojson files aside from the district geometry, number, and name. If we like this direction we can clean up the geojson files to just contain the needed info.

I believe the intent is to make a dropdown to allow users to select a year. For the sake of keeping this pr manageable, right now I've hardcoded the year and the datafile to read from. You can generate the data file by running the following in the `makedata/` dir (after having followed the setup in the README):
`pipenv shell`
`collectFromFile -f 2015 -l 2015`

Notably, using the data from the collectFromFile CLI for 2015 doesn't match up with the existing geojson data for 2015-2016 that is on the current site. @mscarey do you expect it to? If so, I'll look into this.

Also, are there any existing javascript tests for this project? If not, I'll work on creating some. Just wanted to make sure I wasn't duplicating work. I'd like to get some tests in place before merging this.

Last thing is this: currently the legend has 12 colors, though we actually use 13 (with white in the middle). The current CLI generates data from a scale of 0-10 (so, 11 colors). Do we want to change to 11 colors or stick with 13? I think this is another question for @mscarey .

### CODE REVIEW

**Comment by mscarey** [comment]
I'll look at this code soon. I don't think any Javascript tests exist for the project. There are a few reasons the data won't match up: the new scale function is very different; I think some cells that were previously blank should now have zero; and I think the function that determines when to exclude a statistic as "impossible" has changed. Since the scale was changing anyway, I did think it might be better to reduce the number of colors to 11. I did that partly because [d3's diverging color schemes can only have 11 categories.](https://github.com/d3/d3-scale-chromatic) But I haven't seen the new data on the map, so I don't know if the new categories I chose will look right. Keeping 13 categories wouldn't bother me either.

**Comment by mscarey** [comment]
I think there's a bug where some districts that should have the darkest color of blue are showing up with stripes instead. Under White -> ISS, the farthest district to the west near El Paso is Canutillo ISD. If I load stpp2015.json as a variable d, d[2015]["WHI"]["ISS"][71907] is {C: 1, S: 0}, and d[2015]["ALL"]["ISS"][71907] is {C: 630, S: 0}. Since the scale variable is 0, I expected it to be the darkest shade of blue. To get the number 71907 I looked up "Canutillo" in a file in my repo called simple_base_districts.json...which I see I never uploaded. It has the geometry, district numbers, and names, but no statistics. I'll put that in the topojson directory. Maybe that'll help.

**Comment by rebfrank** [comment]
Nice, seems like a good catch. I'll take a look at that district.

**Comment by rebfrank** [comment]
Aha....I'm just checking if value is "truthy" to determine whether or not to apply stripes, not actually checking if it's null/undefined, so a valid "0" is actually failing the check.

**Pull request merged**
